[GLOBAL]
pants_version = "2.0.0"
backend_packages = ['pants.backend.python']

[python-infer]
inits = true
conftest = true
string_imports = true

[test]
extra_env_vars = ['DJANGO_SETTINGS_MODULE=tests.test_sqlite']
