[GLOBAL]
pants_version = "2.0.0"
backend_packages = ["pants.backend.python"]
build_file_prelude_globs = ["pants_macros.py"]

[python-infer]
inits = true
conftests = true
string_imports = true


[pytest]
execution_slot_var = "PANTS_EXECUTION_SLOT"
