django_tests(
    dependencies = [
        'django/contrib/admin/templates',
        'django/contrib/admin/templatetags/admin_modify.py:../../../',
        'django/forms/templates',
        'django/templatetags/l10n.py:../',
        'django/contrib/sites/migrations',
    ]
)
